# Copyright 2025, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

# Jeff and Jim share a datalab s-jeff with one default shared session
# automatically created. That session will run permanently until stopped by the operator.
# The lab does not use a vcluster and has no workshop files.
# Credentials to storage are expected to exist in a secret "jeff" in the same namespace.
# A Keycloak group, role, and client are created; users "jeff" and "jim" must exist in Keycloak.
# This configuration runs the lab in privileged mode:
# - Security policy: "privileged" → automatically enables Docker with 20 Gi workspace storage.
# - Session quota: increased to 6 Gi memory, 60 Gi storage, budget class "x-large".
# - Kubernetes API access is disabled (kubernetesAccess=false).
# Additionally, two PostgreSQL databases are provisioned for the lab: "prod" and "dev".
apiVersion: pkg.internal/v1beta1
kind: Datalab
metadata:
  name: s-jeff
spec:
  users:
    - jeff
    - jim
  secretName: s-jeff
  sessions:
    - default
  vcluster: false
  quota:
    memory: 6Gi
    storage: 60Gi
    budget: x-large
  files: []
  security:
    policy: privileged
    kubernetesAccess: false
  databases:
    pg0:
      names:
      - dev
      - prod
      storage: 1Gi
      backupStorage: 10Gi