# Copyright 2025, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

# Example 3: Datalab with Git-based files
# ---------------------------------------
# Datalab "ws-eric"
# - Users: ["eric"]
# - Sessions: ["default"] → one WorkshopSession named "default" will be created and started.
# - vcluster: false → no virtual cluster will be provisioned.
# - Files: one Git source → workshop and data files are mounted into the environment.
#   This enables the workshop **tab** in the Educates UI, showing the imported content.
apiVersion: pkg.internal/v1beta1
kind: Datalab
metadata:
  name: s-john
spec:
  users:
  - john
  secretName: john
  sessions:
  - default
  vcluster: false
  files:
  - git:
      url: https://github.com/versioneer-tech/datalab-example
      ref: origin/main
    includePaths:
    - /workshop/**
    - /data/**
    - /README.md
    path: .
