site_name: provider-datalab
site_url: https://versioneer-tech.github.io/provider-datalab/
copyright: "Copyright &copy; 2025, Versioneer"
nav:
  - Home: index.md
  - How-to guides:
    - datalab-educates: how-to-guides/datalab-educates.md
    - datalab-jupyter: how-to-guides/datalab-jupyter.md
  - Reference guides:
    - API: reference-guides/api.md
plugins:
  - search
  - mike
markdown_extensions:
  - admonition
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - search.suggest
    - toc.follow
  custom_dir: imgs
  logo: logo.png
  favicon: favicon.ico
  palette:
    - scheme: default
      primary: white
extra:
  version:
    provider: mike
