# Copyright 2025, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

site_name: provider-datalab
site_url: https://versioneer-tech.github.io/provider-datalab/
repo_url: https://github.com/versioneer-tech/provider-datalab
repo_name: versioneer-tech/provider-datalab
copyright: "Copyright &copy; 2025, Versioneer"
nav:
  - Home: index.md
  - How-to guides:
    - Usage & Concepts: how-to-guides/usage_concepts.md
    - Installation: how-to-guides/installation.md
    - Security: how-to-guides/security.md
  - Reference guides:
    - API: reference-guides/api.md
plugins:
  - search
  - mike
markdown_extensions:
  - admonition
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - search.suggest
    - toc.follow
  logo: imgs/logo.png
  favicon: imgs/favicon.ico
  palette:
    - scheme: default
      primary: white
extra:
  version:
    provider: mike
