# Example 1: Minimal Datalab
# --------------------------
# Datalab "ws-alice"
# - Users: ["alice"]
# - Sessions: none → no runtime will be started automatically.
#   (An operator may patch `spec.sessions` later to add sessions.)
# - vcluster: omitted → default is false, so no virtual cluster.
# - Files: omitted → no workshop files will be injected.
#   This means the workshop **tab is disabled** in the Educates UI.
apiVersion: pkg.internal/v1beta1
kind: Datalab
metadata:
  name: ws-alice
spec:
  users:
  - alice
---
# Example 2: Datalab with vcluster
# --------------------------------
# Datalab "ws-bob"
# - Users: ["bob"]
# - Sessions: ["default"] → one WorkshopSession named "default" will be created and started.
# - vcluster: true → a virtual cluster will be provisioned for this datalab.
# - Files: [] → explicit empty list, so no workshop files.
#   Again, the workshop **tab is disabled** in the Educates UI.
apiVersion: pkg.internal/v1beta1
kind: Datalab
metadata:
  name: ws-bob
spec:
  users:
  - bob
  sessions:
  - default
  vcluster: true
  files: []
---
# Example 3: Datalab with Git-based files
# ---------------------------------------
# Datalab "ws-eric"
# - Users: ["eric"]
# - Sessions: ["default"] → one WorkshopSession named "default" will be created and started.
# - vcluster: false → no virtual cluster will be provisioned.
# - Files: one Git source → workshop and data files are mounted into the environment.
#   This enables the workshop **tab** in the Educates UI, showing the imported content.
apiVersion: pkg.internal/v1beta1
kind: Datalab
metadata:
  name: ws-eric
spec:
  users:
  - eric
  sessions:
  - default
  vcluster: false
  files:
  - git:
      url: https://github.com/versioneer-tech/datalab-example
      ref: origin/main
    includePaths:
    - /workshop/**
    - /data/**
    - /README.md
    path: .
