# Copyright 2026, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-keycloak
spec:
  deploymentTemplate:
    metadata:
      labels:
        runtime: provider-keycloak
    spec:
      replicas: 1
      selector:
        matchLabels:
          runtime: provider-keycloak
      template:
        metadata:
          labels:
            runtime: provider-keycloak
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: package-runtime
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
spec:
  deploymentTemplate:
    metadata:
      labels:
        runtime: provider-kubernetes
    spec:
      replicas: 1
      selector:
        matchLabels:
          runtime: provider-kubernetes
      template:
        metadata:
          labels:
            runtime: provider-kubernetes
        spec:
          serviceAccountName: provider-kubernetes
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: package-runtime
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            # args:
            # - --debug
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-helm
spec:
  deploymentTemplate:
    metadata:
      labels:
        runtime: provider-helm
    spec:
      replicas: 1
      selector:
        matchLabels:
          runtime: provider-helm
      template:
        metadata:
          labels:
            runtime: provider-helm
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: package-runtime
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-python
spec:
  deploymentTemplate:
    metadata:
      labels:
        runtime: function-python
    spec:
      replicas: 1
      selector:
        matchLabels:
          runtime: function-python
      template:
        metadata:
          labels:
            runtime: function-python
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: package-runtime
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-auto-ready
spec:
  deploymentTemplate:
    metadata:
      labels:
        runtime: function-auto-ready
    spec:
      replicas: 1
      selector:
        matchLabels:
          runtime: function-auto-ready
      template:
        metadata:
          labels:
            runtime: function-auto-ready
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: package-runtime
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
